services:
  frankoud.com:
    image: nginx
    volumes:
      - ./app:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:3001:80"
    restart: always

  php:
    build: ./php/
    volumes:
      - ./app:/usr/share/nginx/html
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: greenbanana
      MARIADB_DATABASE: InAudible
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "127.0.0.1:3004:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb