services:
  frankoud.com:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - frankoud.com

networks:
  frankoud.com:
    name: frankoud.com
    driver: bridge
