services:
  frankoud.com:
    image: nginx
    volumes:
      - ./app:/usr/share/nginx/html
    ports:
      - "127.0.0.1:3001:80"
    restart: unless-stopped
  php:
    image: php:8.2-fpm
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
