services:
  frankoud.com:
    image: nginx
    volumes:
      - ./app:/usr/share/nginx/html
#    networks:         â<- Change this to expose a port on 127.0.0.1
#      - frankoud.com

networks:
  frankoud.com:
    name: frankoud.com
    driver: bridge
