services:
  frankoud.com:
    image: nginx
    volumes:
      - ./app:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:3001:80"
    restart: unless-stopped

  php:
    build: ./php/
    volumes:
      - ./app:/usr/share/nginx/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: greenbanana
      MARIADB_DATABASE: InAudible
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "127.0.0.1:3004:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb